version: '3.6'

services:
  postgres:
    image: postgres:9.6
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432      
    networks:
      - common
  app:
    build:
      context: .
      dockerfile: Dockerfile 
    command: ["/bin/bash", "-c", "dockerize -wait tcp://postgres:5432 -timeout 10s; sleep 5; /app/bin/dates"]
    container_name: dates      
    ports:
      - 3333:3333
    restart: on-failure    
    networks:
      - common
networks:
  common: